### PR TITLE
Fix creation of custom container with custom configuration

### PR DESCRIPTION
**Pull request by keijokapp**
Hardcoded parameters (types) of instantiateContainer methods.

### CODE REVIEW

**Comment by martinpaljak** [comment]
Signed-off-by: Keijo Kapp <keijo.kapp@gmail.ee> <- is this real ?

**Comment by keijokapp** [comment]
No, sorry. Fixed in my repo. I don't know exactly how to fix that in the pull request. Should I make new one?

**Comment by martinpaljak** [comment]
push -f to your existing repo which updates the PR.

**Comment by keijokapp** [comment]
Yup, fixed. I didn't know the commits in a pull requests update automatically

**Comment by rvillido** [comment]
Thanks for the pull request. Could you also include unit tests that would test the bug/feature that you fixed?

We are doing Test Driven Development (as much as we can) and we need to make sure that future changes and refactorings would not break anything.

**Comment by keijokapp** [comment]
Ok. I've written a test. I'm not very experienced in java & test-driven development.

**Comment by rvillido** [comment]
I merged your changes to the master branch.

There was a small bug I fixed with opening custom containers from stream and I added extra unit tests for covering all the cases.

This functionality will be available in the release after the next 1.0.0 release. We won't be able to include it to the 1.0.0, because we have done a lot of testing with RC and RC2 and don't want to include any untested functionality to the stable release.

Github doesn't recognize that I have merged the pull request and thinks this branch has merge conflicts (probably because of my additional changes), so I will just close it myself.

Thanks for your effort and looking forward for more stuff.

**Pull request closed without merging**
